### ISSUE TITLE
About Training-Free setting

### ISSUE THREAD

**Issue by winnerwu6** [ltttpku/ADA-CM#1]
您好，当我在HICO-DET上运行您提供的 train free 执行命令时，会报错显示缺少一些文件，如下
_**FileNotFoundError: [Errno 2] No such file or directory: 'hicodet_pkl_files/hicodet_train_bbox_R50.p'**_
不知您是否能提供更多的帮助，谢谢！！！

**Comment by echo-654** [comment]
I have encountered the same problem, could you please provide these '.p' files, thank you!

**Comment by ltttpku** [comment]
Thanks for the feedback.

I've uploaded the pickle file for the bounding boxes [here](https://drive.google.com/file/d/1xHGr36idtYSzMYGHKvvxMJyTiaq317Ev/view) . See Readme for more details!
