### ISSUE TITLE
ModuleNotFoundError: No module named 'd_detr'

### ISSUE THREAD

**Issue by slcheng97** [ltttpku/ADA-CM#10]
When I run your code, I encountered the following problem:
```
Traceback (most recent call last):
  File "/home/slcheng/Documents/code/ADA-CM/main_tip_ye.py", line 22, in <module>
    from upt_tip_cache_model_free_ye import build_detector
  File "/home/slcheng/Documents/code/ADA-CM/upt_tip_cache_model_free_ye.py", line 35, in <module>
    from d_detr.models import build_model as build_model_d_detr
ModuleNotFoundError: No module named 'd_detr'
```
Could you tell me how to solve this problem? 
Thanks！

**Comment by ltttpku** [comment]
The import statement `from d_detr.models import build_model as build_model_d_detr` can be safely removed since the model incorporates the DETR model.

**Comment by slcheng97** [comment]
Thank you for your valuable and timely suggestions! 
It works now.
