### ISSUE TITLE
The criteria for selecting instances

### ISSUE THREAD

**Issue by slcheng97** [ltttpku/ADA-CM#11]
I'm intrigued by your method of extracting human/subject/union ROI features. Specifically, I'm curious about your approach to determining the number of instances to store in the concept memory, as well as the criteria for selecting instances to include or exclude from the concept memory. I also found tha same issue in #4 . Would it be possible for you to share the code you used for this purpose?

**Comment by ltttpku** [comment]
Hi, I don't plan to release the code for extracting features from human, subject, or union regions of interest (ROI). The features are extracted using ROI pooling on the feature map generated by CLIP, utilizing bounding boxes provided by DETR. This process should not be too difficult to implement.
For the strategy of constructing concept-guided memory, you can refer to our [supplemantary material](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Lei_Efficient_Adaptive_Human-Object_ICCV_2023_supplemental.pdf) for more details.

**Comment by CL2LC** [comment]
Friend, have you succeeded in replicating it? I'm interested in that part, too
