### ISSUE TITLE
Issues with attention visualization

### ISSUE THREAD

**Issue by ZMH-SDUST** [ltttpku/ADA-CM#12]
Hello, When calling fuction 'visualize_entire_image()' in the 'inference.py' file for attention visualization, how do I get output['attn_maps']? There doesn't seem to be such a dictionary in the initial code?

**Comment by ltttpku** [comment]
We haven't provided the code for visualizing the attention maps in this project. However, you can try to extract them from the appropriate location in the code and visualize them yourself.
