### ISSUE TITLE
Cannot Donwload hicodet

### ISSUE THREAD

**Issue by y29jiao** [ltttpku/ADA-CM#14]
the source files were removed from Google Drive. Currently, I cannot use download.sh to download the dataset. 
<img width="1369" alt="image" src="https://github.com/user-attachments/assets/fda7d796-8a85-4163-8ace-d70bf2c38e07">

**Comment by ltttpku** [comment]
Can you try this [link](https://drive.google.com/file/d/1dUByzVzM6z1Oq4gENa1-t0FLhr0UtDaS/view) to download the hico-det dataset?
