### ISSUE TITLE
How do you encode human/object features ? And what's the meaning of ex_hidden_states in batch[1]?

### ISSUE THREAD

**Issue by JeffreyYzh** [ltttpku/ADA-CM#3]
HELLO, really good work!But when I read your code, I am confused about your region encoding.As you mention in your paper, CLIP is used to encode the human and object region.But I only see you split the whole img embedded by CLIP, and allocate them to represent human, object and union feature. The code can be refered below, why does it work?

Besides, what is the meaning of ex_hidden_states in every batch of dataset?

```
lens = local_features.shape[0]
            feat1 = local_features[:lens//3,:] # human features
            feat2 = local_features[lens//3:lens//3*2,:] # object features
            feat3 = local_features[lens//3*2:,:]  # union features
            feat1 = feat1 / feat1.norm(dim=-1, keepdim=True)
            feat2 = feat2 / feat2.norm(dim=-1, keepdim=True)
            feat3 = feat3 / feat3.norm(dim=-1, keepdim=True)
```

**Comment by ltttpku** [comment]
Thank you for your interest in our work! 
1. In the Training-Free mode, _we encode the cropped images of humans, objects and unions by CLIP and then split it to represent human, object and union features._ Specifically, we first utilize DETR to extract bounding boxes of humans, objects, and unions, e.g., ```sub_boxes, obj_boxes, union_boxes```. Then we crop the images using the above bounding boxes and stack the cropped images, i.e., ```all_images = torch.cat([all_images_human,all_images_object,all_images_union])```. At last, we utilize CLIP to encode ```all_images``` to get ```local_features``` you refer to. Thus, the variable ```local_features``` is actually the concatenation of $[f_{hum}^0, f_{hum}^1, ..., f_{hum}^N, f_{obj}^0, f_{obj}^1, ..., f_{obj}^N, f_{uni}^0, f_{uni}^1, ..., f_{uni}^N]$.
2. The ```ex_hidden_states``` is the output of the last layer of DETR for each detected instance, which is not used and can be safely removed.
