### ISSUE TITLE
pre-feature

### ISSUE THREAD

**Issue by soberguo** [ltttpku/ADA-CM#4]
Hello, I'm very interested in the pre-feature you extracted, I don't know how you extracted it? I see that your code has extract_memory parts, but I can't run it correctly

**Comment by ltttpku** [comment]
Thank you for your interest in our work!

We are currently using pre-trained DETR to extract bounding boxes for humans, objects, and unions. Additionally, we utilize CLIP to extract features from cropped images. Feel free to use our provided pre-extract features.

I will clean the code for preprocessing in the near future, as I have recently been working on meeting deadlines.

**Comment by soberguo** [comment]
Thanks！Looking forward to your improvement.
