### ISSUE TITLE
zero-shot setting

### ISSUE THREAD

**Issue by yaoyaosanqi** [ltttpku/ADA-CM#5]
Thank you for your excellent work. We have some questions about zero-shot. We noticed that args.num_classes is either 117 or 600. Which is used in this work? Then, can you briefly describe the code flow of zero-shot?

**Comment by ltttpku** [comment]
Thanks for taking an interest in our work.

We set `num_classes` to 117 in the zero-shot setting on HICO-DET.

For the zero-shot setting, we filter the HOI annotations related to the unseen HOI classes in the DataFactory (refer to the code between  [line 138](https://github.com/ltttpku/ADA-CM/blob/636a60696c2a2978e38bcb9bbca8b9ba9cdc57a3/utils_tip_cache_and_union_finetune.py#L138) and [line 159](https://github.com/ltttpku/ADA-CM/blob/636a60696c2a2978e38bcb9bbca8b9ba9cdc57a3/utils_tip_cache_and_union_finetune.py#L159)). During training, the unseen classes are ignored thanks to `object_to_target` (initialized [here](https://github.com/ltttpku/ADA-CM/blob/636a60696c2a2978e38bcb9bbca8b9ba9cdc57a3/main_tip_finetune.py#L259)).

**Comment by yaoyaosanqi** [comment]
Thanks!
