### ISSUE TITLE
Invalid download link

### ISSUE THREAD

**Issue by dekrt** [ltttpku/ADA-CM#6]
when I trying to download the pre-extracted bboxes  `"the pre-extracted bboxes from [HERE](https://drive.google.com/file/d/1xHGr36idtYSzMYGHKvvxMJyTiaq317Ev/view?usp=sharing)."`, it said `Sorry, the file you requested does not exist.`

**Comment by ltttpku** [comment]
I updated the download link in Readme just now. Apologies for the wait.
