### ISSUE TITLE
could you provide zero-shot pretrained weight?

### ISSUE THREAD

**Issue by OreoChocolate** [ltttpku/ADA-CM#7]
Thank you for your excellent work. 

I want to evaluate on zero-shot setting but there are only supervised pretrained weights.
could you provide zero-shot pretrained weight for the finetuned models?

Thank you in advance!

**Comment by ltttpku** [comment]
Apologies for the delay. I've been occupied by a few things recently. I will try to spend more time to replicate the reported number and provide the model weight in zero-shot settings in the next few days.

**Comment by ltttpku** [comment]
Apologies for the delay. I'm currently working on another project. In the meantime, you can try training the zero-shot version by adding the commands `--zs` and -`-zs_type rare_first` during training. Please don't hesitate to reach out if you have any further questions!
