### ISSUE TITLE
V-COCO Evaluate

### ISSUE THREAD

**Issue by aqingcv** [ltttpku/ADA-CM#9]
For V-COCO, you use the utilities provided by [Gupta et al](https://github.com/s-gupta/v-coco#evaluation), but the length of the test dataset is 4532 in your code，this means that the resulting cache.pkl contains only 4532 outputs. However, in the utilities provided by [Gupta et al.](https://github.com/s-gupta/v-coco#evaluation), the images in the v-coco/data/splits/vcoco_test.ids is 4946, which is not equal to the 4532. Will this affect the final test results? Thanks.

**Comment by ltttpku** [comment]
Hi, I follow this [repo](https://github.com/fredzzhang/vcoco) to load the v-coco dataset, where the images without valid human-object interactions are removed from the scope of `__len__`, `__getitem__` etc.
